# 头部菜单，title: link
menu:
  Github: https://github.com/BruceLanCode
  Twitter: https://twitter.com

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - https://link.hhtjim.com/163/506650377.mp3
  - https://link.hhtjim.com/163/430685732.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: /img/index-cover.jpg

# 默认文章封面图
cover: /img/Blog.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: 'e36e2e5be97c29cb20cb'
    # 应用秘钥
    clientSecret: 'fb99a700bd2a4265175a47693f85abe676182a8f'
    # issue仓库名
    repo: 'blog'
    # Github名
    owner: 'BruceLanCode'
    # Github名
    admin: ['BruceLanCode']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: Bruce blog Font-end development

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.jpg

# rss文件
rss: atom.xml
